### PR TITLE
[fix] Updated config to use angular constant

### PR DESCRIPTION
**Pull request by alex-deaconu**
Changed config value to use Angular constant. This should fix constant naming conflict in the Style guide - https://github.com/Rise-Vision/style-guide/issues/111.

@donnapep and/or @stulees please review. Thanks.

### CODE REVIEW

**Comment by stulees** [comment]
@alex-deaconu Looks good but I'm pretty sure the style-guide issue is because of my recent update to component-storage-selector which was a similar update you have just done (config module with a constant). The app of style guide is missing my `storage-selector.config` module dependency and it will likely now need your `financial.config` module too after style-guide gets automatically built from this PR. I can add both of them to style-guide. :+1:

**Comment by alex-deaconu** [comment]
@stulees actually I disagree. In this component the config modules are being added to the service, so all is well in that regard. The stoage-selector also adds the config module. 

The conflict in the style-guide was over the CONFIG global constant we were creating. Your widget's angular code was not being initialized because CONFIG !== null. 

Thanks.

**Comment by stulees** [comment]
@alex-deaconu Oh okay. Lets give it a try then, thanks.

**Comment by alex-deaconu** [comment]
@stulees will merge and see what happens when the style-guide build is triggered. Thanks.

**Pull request merged**
